/**
 * The student is permitted to add content to this file.  This file will 
 * be part of the submission for grading.
 * 
 * It isnot required to add anything to this file.
 */
 
// This may be modified but must be a type that will contain the largest number
// that could be generated by the array filling code in main.cu.
// Using an invalid data type will results in a 20% gading penalty.
#define DTYPE short
extern int pad_size;
#define TILE 16384

// Add any additional #include headers or helper macros needed

